#!/bin/sh

./Allclean

cd ${0%/*} || exit 1    # run from this directory



# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh
runApplication setFields
#runApplication $application
runApplication $FOAM_USER_APPBIN/my_icoFoam

echo Run Complete. Starting Paraview...

runApplication paraFoam

echo Finished.
# ----------------------------------------------------------------- end-of-file
